# Generated by Django 4.1 on 2022-09-23 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0002_user_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='Image_Link',
        ),
    ]
