# Generated by Django 3.2.10 on 2022-10-08 23:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0005_auto_20221007_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts_info',
            name='Audio_File',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts_info',
            name='Image_File',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
