# Generated by Django 3.2.10 on 2022-10-08 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0006_auto_20221008_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts_info',
            name='Audio_File',
        ),
        migrations.RemoveField(
            model_name='posts_info',
            name='Image_File',
        ),
    ]
