# Generated by Django 3.2.10 on 2022-10-09 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0007_auto_20221008_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts_info',
            name='date',
        ),
    ]
