# Generated by Django 3.2.10 on 2022-10-09 00:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0008_remove_posts_info_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts_info',
            name='User_Idd',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
