# Generated by Django 3.2.10 on 2022-10-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0009_posts_info_user_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts_info',
            name='Text',
            field=models.CharField(max_length=500),
        ),
    ]
