# Generated by Django 3.2.10 on 2022-10-09 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0011_alter_posts_info_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts_info',
        ),
    ]
