# Generated by Django 3.2.10 on 2022-10-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0013_posts_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='Password',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
