# Generated by Django 3.2.10 on 2022-10-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0015_auto_20221009_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Id', models.CharField(max_length=100)),
                ('Post_Id', models.CharField(max_length=100)),
                ('User_Idd', models.CharField(max_length=100)),
                ('Text', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
