# Generated by Django 3.2.10 on 2022-10-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0017_auto_20221013_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Id', models.CharField(max_length=100)),
                ('Follower_Id', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user_info',
            name='Followers',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
