# Generated by Django 3.2.10 on 2022-10-18 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0018_auto_20221016_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_follower',
            name='date',
        ),
    ]
