# Generated by Django 3.2.10 on 2022-10-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0019_remove_user_follower_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_messeges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sender_Id', models.CharField(max_length=100)),
                ('Reciever_Id', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Content', models.CharField(max_length=500)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
