# Generated by Django 3.2.10 on 2022-10-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0022_auto_20221018_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_list',
            name='Time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_list',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
