# Generated by Django 3.2.10 on 2022-10-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0024_auto_20221019_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sender_Id', models.CharField(max_length=100)),
                ('Reciever_Id', models.CharField(max_length=100)),
                ('Idd_Id', models.CharField(max_length=500)),
                ('Type', models.CharField(max_length=100)),
                ('Content', models.CharField(max_length=500)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
