# Generated by Django 3.2.10 on 2022-10-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0026_auto_20221024_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_api',
            name='Link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
