# Generated by Django 3.2.10 on 2022-10-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0027_message_api_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_api',
            name='Time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message_api',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
