# Generated by Django 3.2.10 on 2022-10-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0028_auto_20221026_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_api',
            name='Time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message_api',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
